from __future__ import annotations

from collections import deque
from dataclasses import dataclass


@dataclass(frozen=True)
class SeedBook:
    title: str
    author: str


@dataclass(frozen=True)
class CategoryProfile:
    label: str
    themes: tuple[str, ...]
    key_idea_templates: tuple[str, ...]
    practical_templates: tuple[str, ...]
    reflection_template: str


CATEGORY_ORDER = (
    "estrategia",
    "ficcao_classica",
    "psicologia",
    "filosofia",
    "economia",
    "ficcao_moderna",
    "geopolitica",
    "historia",
    "ciencia",
    "sociologia",
    "biografia",
)


PROFILES: dict[str, CategoryProfile] = {
    "estrategia": CategoryProfile(
        label="Lideranca, estrategia e decisao",
        themes=(
            "priorizacao e foco em alavancas decisivas",
            "lideranca servidora e construcao de confianca",
            "negociacao, influencia e leitura de contexto",
            "execucao disciplinada e aprendizado em ciclos curtos",
            "estrategia competitiva e escolhas de posicionamento",
            "gestao de equipe, conflito e accountability",
        ),
        key_idea_templates=(
            "A obra trata {theme} como pratica deliberada, nao como talento espontaneo.",
            "Resultados consistentes dependem de criterios claros para decidir sob pressao.",
            "A qualidade da execucao aparece no desenho de rotina, prioridades e feedback.",
            "Contexto, cultura e incentivos alteram o efeito de qualquer metodo proposto.",
            "A principal licao e transformar intuicao em processo observavel e ajustavel.",
        ),
        practical_templates=(
            "Escolher uma decisao recorrente da semana e explicitar qual criterio guiara a escolha.",
            "Revisar uma reuniao, projeto ou conflito recente usando a lente de {theme}.",
            "Definir um experimento pequeno para testar a ideia central do livro nos proximos 7 dias.",
        ),
        reflection_template="Em que area do seu trabalho {theme} precisa deixar de ser intuicao e virar metodo?",
    ),
    "ficcao_classica": CategoryProfile(
        label="Ficcao classica",
        themes=(
            "honra, desejo e conflito moral",
            "classe, ambicao e mobilidade social",
            "culpa, consciencia e responsabilidade",
            "memoria, tempo e perda",
            "poder, autoridade e destino",
            "amor, convencao e autonomia",
            "civilizacao, violencia e limite humano",
            "identidade, aparencia e autoengano",
        ),
        key_idea_templates=(
            "A narrativa usa {theme} para expor como escolhas pessoais colidem com expectativas sociais.",
            "Personagens e ambiente funcionam como laboratorio moral para observar motivacoes, ilusoes e custos.",
            "O conflito central mostra que nenhuma decisao importante surge isolada de classe, tempo e instituicoes.",
            "A forma literaria amplia o tema ao combinar simbolo, ritmo e ponto de vista.",
            "A obra permanece atual porque transforma dilemas historicos em perguntas permanentes sobre a condicao humana.",
        ),
        practical_templates=(
            "Anotar uma decisao critica de personagem e comparar com um dilema contemporaneo parecido.",
            "Registrar que regra social, moral ou economica estrutura o conflito principal da narrativa.",
            "Escrever uma pergunta de leitura sobre {theme} para orientar a proxima releitura ou discussao.",
        ),
        reflection_template="Que aspecto de {theme} aparece hoje na sua vida sem se anunciar de forma explicita?",
    ),
    "ficcao_moderna": CategoryProfile(
        label="Ficcao moderna e contemporanea",
        themes=(
            "vigilancia, controle e erosao da liberdade",
            "pertencimento, deslocamento e identidade",
            "memoria, trauma e reconstrucao de sentido",
            "violencia politica e custo humano da historia",
            "linguagem, percepcao e realidade instavel",
            "familia, desejo e silencios afetivos",
            "colonialismo, poder e conflito social",
            "tecnologia, isolamento e fragilidade do eu",
        ),
        key_idea_templates=(
            "O livro transforma {theme} em experiencia narrativa concreta, nao em tese abstrata.",
            "A forca da obra esta em mostrar como estruturas historicas e afetivas moldam a vida comum.",
            "O narrador, os cortes de tempo e os simbolos alteram a forma como o leitor percebe o conflito.",
            "A narrativa recusa respostas simples e obriga o leitor a sustentar ambiguidade e tensao.",
            "A leitura rende mais quando o enredo e tratado como lente para ler o presente, nao apenas como trama.",
        ),
        practical_templates=(
            "Identificar uma cena em que {theme} aparece com nitidez e registrar por que ela permanece atual.",
            "Comparar a perspectiva de dois personagens para entender como contexto altera julgamento moral.",
            "Levar uma pergunta da obra para o cotidiano: que mecanismo social parecido voce observa hoje?",
        ),
        reflection_template="Que situacao atual faz voce perceber {theme} de maneira menos abstrata e mais concreta?",
    ),
    "filosofia": CategoryProfile(
        label="Filosofia",
        themes=(
            "virtude, carater e vida boa",
            "liberdade, dever e responsabilidade",
            "verdade, conhecimento e limite da razao",
            "poder, ordem politica e legitimidade",
            "absurdo, finitude e sentido da existencia",
            "autocultivo, serenidade e governo de si",
            "linguagem, metodo e formacao do juizo",
        ),
        key_idea_templates=(
            "A obra organiza {theme} como problema filosofico central, exigindo definicao rigorosa de termos.",
            "O argumento principal avanca por contraste entre intuicoes comuns e exame conceitual mais exigente.",
            "Ler filosofia aqui significa testar premissas, nao apenas concordar com conclusoes elegantes.",
            "A pergunta do autor continua viva porque reaparece em escolhas eticas, politicas e pessoais.",
            "O ganho da leitura esta em transformar opiniao vaga em criterio de interpretacao mais consistente.",
        ),
        practical_templates=(
            "Escrever em uma frase qual tese do autor parece mais convincente e qual ainda resiste a voce.",
            "Aplicar a lente de {theme} a uma decisao real antes de agir por impulso ou costume.",
            "Registrar uma premissa do livro que muda a forma de formular uma pergunta antiga.",
        ),
        reflection_template="Qual suposicao sua sobre {theme} esta forte demais para continuar sem exame?",
    ),
    "psicologia": CategoryProfile(
        label="Psicologia e comportamento",
        themes=(
            "vieses, julgamento e tomada de decisao",
            "emocao, regulacao e autoconsciencia",
            "motivacao, habito e persistencia",
            "identidade, relacao e vinculo afetivo",
            "trauma, memoria e adaptacao",
            "felicidade, sentido e bem-estar",
            "comportamento social e pressao de contexto",
        ),
        key_idea_templates=(
            "O livro examina {theme} conectando mecanismo mental, comportamento observavel e contexto.",
            "A principal contribuicao esta em mostrar como o erro humano segue padroes recorrentes, nao falhas aleatorias.",
            "Percepcao, emocao e ambiente interagem mais do que a intuicao costuma admitir.",
            "A leitura convida a trocar explicacoes morais simplistas por hipoteses mais precisas sobre comportamento.",
            "Aplicar a obra pede observacao de processo, nao apenas busca de resultado imediato.",
        ),
        practical_templates=(
            "Observar durante a semana uma situacao em que {theme} apareca antes de tentar corrigi-la.",
            "Descrever um gatilho, uma resposta e uma consequencia ligados ao ponto central do livro.",
            "Testar um ajuste simples de ambiente, linguagem ou rotina para reduzir erro recorrente.",
        ),
        reflection_template="Qual padrao de {theme} voce reconhece hoje com mais clareza do que reconhecia antes?",
    ),
    "economia": CategoryProfile(
        label="Economia e negocios",
        themes=(
            "incentivos, mercado e coordenacao social",
            "desigualdade, distribuicao e mobilidade",
            "crises, risco e instabilidade financeira",
            "desenvolvimento, instituicoes e prosperidade",
            "estado, politica publica e capacidade de investimento",
            "trabalho, produtividade e estrutura de longo prazo",
        ),
        key_idea_templates=(
            "A obra interpreta {theme} observando incentivos, restricoes e efeitos agregados das escolhas individuais.",
            "O argumento economico ganha forca quando conecta teoria, historia e consequencias nao intencionais.",
            "Instituicoes importam porque alteram quem suporta risco, quem captura ganho e quem fica sem voz.",
            "Boa leitura economica exige comparar trade-offs, e nao apenas repetir slogans de mercado ou de Estado.",
            "O livro ajuda a enxergar mecanismos por tras de indicadores que muitas vezes aparecem de forma abstrata.",
        ),
        practical_templates=(
            "Mapear uma decisao publica ou empresarial recente usando a lente de {theme}.",
            "Perguntar quem ganha, quem perde e quais incentivos mudam quando uma regra se altera.",
            "Registrar um indicador economico que voce acompanha mal e que merece interpretacao mais cuidadosa.",
        ),
        reflection_template="Que debate atual sobre {theme} voce tende a simplificar mais do que deveria?",
    ),
    "geopolitica": CategoryProfile(
        label="Geopolitica e relacoes internacionais",
        themes=(
            "territorio, recursos e restricoes geograficas",
            "equilibrio de poder e ordem internacional",
            "guerra, dissuasao e percepcao de seguranca",
            "imperios, hegemonia e transicao de poder",
            "energia, cadeias globais e disputa estrategica",
            "instituicoes, diplomacia e legitimidade externa",
        ),
        key_idea_templates=(
            "O livro aborda {theme} mostrando que estrategia internacional nunca depende apenas de intencoes declaradas.",
            "Capacidade material, geografia e percepcao de risco moldam o comportamento dos Estados.",
            "A obra ajuda a distinguir retorica diplomatica de interesse estrategico efetivo.",
            "Nenhum arranjo de poder e estavel por si; equilibrio precisa ser continuamente negociado e sustentado.",
            "A leitura melhora quando eventos atuais sao comparados com padroes historicos de competicao e acomodacao.",
        ),
        practical_templates=(
            "Escolher um conflito ou rivalidade atual e listar como {theme} aparece de forma concreta.",
            "Separar, em uma noticia internacional, o que e discurso domestico e o que e sinal estrategico.",
            "Registrar um mapa mental simples com atores, interesses, restricoes e riscos de escalada.",
        ),
        reflection_template="Que evento internacional recente voce entende melhor quando olha para {theme} em vez de olhar apenas para narrativas oficiais?",
    ),
    "historia": CategoryProfile(
        label="Historia e civilizacao",
        themes=(
            "mudanca institucional e longa duracao",
            "imperios, revolucoes e reorganizacao do poder",
            "colonizacao, violencia e memoria historica",
            "tecnologia, ambiente e transformacao social",
            "migracao, trabalho e formacao de hierarquias",
            "cultura politica, conflito e aprendizagem historica",
        ),
        key_idea_templates=(
            "A obra examina {theme} reconstruindo processos, rupturas e continuidades ao longo do tempo.",
            "Historia aqui nao e colecao de datas; e explicacao causal apoiada em contexto, escala e comparacao.",
            "O livro mostra como instituicoes sobrevivem a individuos e continuam produzindo efeitos no presente.",
            "Boas licoes historicas surgem quando se evita anacronismo e se respeita a logica do periodo estudado.",
            "A leitura amplia repertorio para interpretar mudancas atuais sem cair em presentismo facil.",
        ),
        practical_templates=(
            "Montar uma linha curta de causa e efeito para um processo historico discutido na obra.",
            "Comparar um problema atual com o antecedente historico mais proximo sugerido por {theme}.",
            "Registrar que conceito, instituicao ou fronteira do presente nasceu do periodo estudado.",
        ),
        reflection_template="Que leitura sua do presente muda quando {theme} e colocado em perspectiva historica mais ampla?",
    ),
    "ciencia": CategoryProfile(
        label="Ciencia, tecnologia e sistemas",
        themes=(
            "metodo cientifico, evidencia e limite da inferencia",
            "complexidade, sistema e efeitos nao lineares",
            "vida, evolucao e adaptacao",
            "tecnologia, informacao e reorganizacao do mundo",
            "saude, risco e decisao sob incerteza",
            "medicao, previsao e erro estatistico",
        ),
        key_idea_templates=(
            "A obra trata {theme} como exercicio de observacao rigorosa, teste e revisao de modelo.",
            "O ganho intelectual do livro esta em separar dado, interpretacao e limite metodologico.",
            "Sistemas complexos respondem mal a intuicoes lineares e a excesso de confianca.",
            "A leitura reforca que conhecimento robusto nasce de metodo, nao de autoridade isolada.",
            "Aplicar a obra significa fazer perguntas melhores antes de aceitar uma conclusao sedutora.",
        ),
        practical_templates=(
            "Escolher uma noticia ou opiniao forte e separar o que e evidencia do que e interpretacao.",
            "Mapear um sistema cotidiano em termos de entrada, feedback, atraso e efeito colateral.",
            "Anotar uma decisao pessoal ou profissional em que {theme} pede mais prudencia analitica.",
        ),
        reflection_template="Em que situacao voce mais precisa da disciplina de {theme} para pensar com menos impulso?",
    ),
    "sociologia": CategoryProfile(
        label="Sociologia e cultura",
        themes=(
            "normas sociais, performance e papel publico",
            "midia, linguagem e disputa por atencao",
            "classe, desigualdade e reproducao de poder",
            "genero, raca e experiencia social",
            "instituicoes, vigilancia e disciplinamento",
            "consumo, identidade e cultura de massa",
        ),
        key_idea_templates=(
            "O livro analisa {theme} mostrando como a vida social organiza percepcao, comportamento e oportunidade.",
            "O que parece escolha individual muitas vezes e resposta a norma, instituicao ou hierarquia previa.",
            "A obra convida a observar linguagem, ritual e simbolo como tecnologias de poder.",
            "A leitura fica mais forte quando exemplos do cotidiano sao relidos como fenomenos estruturais.",
            "O principal valor do livro esta em tornar visivel aquilo que a rotina costuma naturalizar.",
        ),
        practical_templates=(
            "Observar uma interacao cotidiana e identificar que norma invisivel organiza o comportamento das partes.",
            "Registrar um exemplo recente em que {theme} apareceu na midia, no trabalho ou na cidade.",
            "Transformar uma indignacao difusa em pergunta sociologica mais precisa sobre estrutura e incentivo.",
        ),
        reflection_template="Que parte de {theme} voce naturalizou tanto que quase deixou de enxergar?",
    ),
    "biografia": CategoryProfile(
        label="Biografias e memorias",
        themes=(
            "formacao de carater sob pressao",
            "trajetoria, ambicao e custo da excelencia",
            "lideranca, contexto e decisao historica",
            "vulnerabilidade, perda e reconstrucao pessoal",
            "aprendizado, trabalho e reinvencao",
            "memoria, identidade e interpretacao da propria vida",
        ),
        key_idea_templates=(
            "A obra aborda {theme} pela trajetoria concreta de uma vida situada em contexto historico especifico.",
            "Biografia forte nao oferece manual; oferece criterio ao mostrar escolha, consequencia e limite.",
            "O interesse do livro esta tanto no personagem quanto nas instituicoes e epocas que o cercam.",
            "A narrativa ajuda a distinguir talento, oportunidade, disciplina e contingencia.",
            "Ler memorias e biografias pede atencao ao ponto de vista e ao que fica enfatizado ou omitido.",
        ),
        practical_templates=(
            "Registrar uma escolha decisiva do personagem central e o custo invisivel associado a ela.",
            "Comparar a trajetoria lida com uma decisao propria que exige mais paciencia estrategica.",
            "Anotar que parte de {theme} dependeu de contexto historico e que parte dependeu de carater.",
        ),
        reflection_template="Que criterio de vida ou trabalho fica mais claro para voce quando observa {theme} em uma trajetoria real?",
    ),
}
SEED_BOOKS: dict[str, tuple[SeedBook, ...]] = {
    "estrategia": (
        SeedBook("Habitos Atomicos", "James Clear"),
        SeedBook("Essencialismo", "Greg McKeown"),
        SeedBook("Trabalho Focado", "Cal Newport"),
        SeedBook("Os 7 Habitos das Pessoas Altamente Eficazes", "Stephen R. Covey"),
        SeedBook("Comece pelo Porque", "Simon Sinek"),
        SeedBook("O Monge e o Executivo", "James C. Hunter"),
        SeedBook("Como Fazer Amigos e Influenciar Pessoas", "Dale Carnegie"),
        SeedBook("A Unica Coisa", "Gary Keller e Jay Papasan"),
        SeedBook("Principios", "Ray Dalio"),
        SeedBook("Gestao do Amanha", "Sandro Magaldi e Jose Salibi Neto"),
        SeedBook("Nunca Divida a Diferenca", "Chris Voss"),
        SeedBook("Good Strategy Bad Strategy", "Richard Rumelt"),
        SeedBook("The Effective Executive", "Peter Drucker"),
        SeedBook("Team of Teams", "Stanley McChrystal"),
        SeedBook("Extreme Ownership", "Jocko Willink e Leif Babin"),
        SeedBook("The Five Dysfunctions of a Team", "Patrick Lencioni"),
        SeedBook("Good to Great", "Jim Collins"),
        SeedBook("Blue Ocean Strategy", "W. Chan Kim e Renee Mauborgne"),
        SeedBook("Competitive Strategy", "Michael Porter"),
        SeedBook("The Lean Startup", "Eric Ries"),
        SeedBook("Measure What Matters", "John Doerr"),
        SeedBook("Zero to One", "Peter Thiel"),
        SeedBook("The Hard Thing About Hard Things", "Ben Horowitz"),
        SeedBook("Only the Paranoid Survive", "Andrew Grove"),
        SeedBook("The Art of Strategy", "Avinash K. Dixit e Barry J. Nalebuff"),
    ),
    "ficcao_classica": (
        SeedBook("Dom Quixote", "Miguel de Cervantes"),
        SeedBook("Hamlet", "William Shakespeare"),
        SeedBook("Macbeth", "William Shakespeare"),
        SeedBook("Rei Lear", "William Shakespeare"),
        SeedBook("Otelo", "William Shakespeare"),
        SeedBook("Orgulho e Preconceito", "Jane Austen"),
        SeedBook("Emma", "Jane Austen"),
        SeedBook("Razao e Sensibilidade", "Jane Austen"),
        SeedBook("Persuasao", "Jane Austen"),
        SeedBook("Jane Eyre", "Charlotte Bronte"),
        SeedBook("O Morro dos Ventos Uivantes", "Emily Bronte"),
        SeedBook("Middlemarch", "George Eliot"),
        SeedBook("Grandes Esperancas", "Charles Dickens"),
        SeedBook("David Copperfield", "Charles Dickens"),
        SeedBook("Bleak House", "Charles Dickens"),
        SeedBook("Um Conto de Duas Cidades", "Charles Dickens"),
        SeedBook("Madame Bovary", "Gustave Flaubert"),
        SeedBook("Os Miseraveis", "Victor Hugo"),
        SeedBook("O Corcunda de Notre-Dame", "Victor Hugo"),
        SeedBook("Germinal", "Emile Zola"),
        SeedBook("O Vermelho e o Negro", "Stendhal"),
        SeedBook("Pai Goriot", "Honore de Balzac"),
        SeedBook("Ilusoes Perdidas", "Honore de Balzac"),
        SeedBook("Moby-Dick", "Herman Melville"),
        SeedBook("A Letra Escarlate", "Nathaniel Hawthorne"),
        SeedBook("Os Irmaos Karamazov", "Fiodor Dostoievski"),
        SeedBook("Crime e Castigo", "Fiodor Dostoievski"),
        SeedBook("O Idiota", "Fiodor Dostoievski"),
        SeedBook("Memorias do Subsolo", "Fiodor Dostoievski"),
        SeedBook("Guerra e Paz", "Leon Tolstoi"),
        SeedBook("Anna Karenina", "Leon Tolstoi"),
        SeedBook("A Morte de Ivan Ilitch", "Leon Tolstoi"),
        SeedBook("Ressurreicao", "Leon Tolstoi"),
        SeedBook("O Processo", "Franz Kafka"),
        SeedBook("O Castelo", "Franz Kafka"),
        SeedBook("A Metamorfose", "Franz Kafka"),
        SeedBook("O Retrato de Dorian Gray", "Oscar Wilde"),
        SeedBook("O Grande Gatsby", "F. Scott Fitzgerald"),
        SeedBook("As Vinhas da Ira", "John Steinbeck"),
        SeedBook("A Leste do Eden", "John Steinbeck"),
        SeedBook("Ratos e Homens", "John Steinbeck"),
        SeedBook("Mrs Dalloway", "Virginia Woolf"),
        SeedBook("Ao Farol", "Virginia Woolf"),
        SeedBook("No Caminho de Swann", "Marcel Proust"),
        SeedBook("O Estrangeiro", "Albert Camus"),
        SeedBook("A Peste", "Albert Camus"),
        SeedBook("O Som e a Furia", "William Faulkner"),
        SeedBook("Absalom, Absalom!", "William Faulkner"),
        SeedBook("O Coracao das Trevas", "Joseph Conrad"),
        SeedBook("Nostromo", "Joseph Conrad"),
        SeedBook("Os Maias", "Eca de Queiros"),
        SeedBook("Buddenbrooks", "Thomas Mann"),
        SeedBook("Effi Briest", "Theodor Fontane"),
        SeedBook("A Educacao Sentimental", "Gustave Flaubert"),
        SeedBook("A Cartuxa de Parma", "Stendhal"),
    ),
    "psicologia": (
        SeedBook("Mindset", "Carol S. Dweck"),
        SeedBook("Rapido e Devagar", "Daniel Kahneman"),
        SeedBook("O Poder do Habito", "Charles Duhigg"),
        SeedBook("Garra (Grit)", "Angela Duckworth"),
        SeedBook("Inteligencia Emocional", "Daniel Goleman"),
        SeedBook("O Jeito Harvard de Ser Feliz", "Shawn Achor"),
        SeedBook("O Homem em Busca de Sentido", "Viktor Frankl"),
        SeedBook("Flow", "Mihaly Csikszentmihalyi"),
        SeedBook("Predictably Irrational", "Dan Ariely"),
        SeedBook("Influence", "Robert Cialdini"),
        SeedBook("Behave", "Robert Sapolsky"),
        SeedBook("The Righteous Mind", "Jonathan Haidt"),
        SeedBook("Stumbling on Happiness", "Daniel Gilbert"),
        SeedBook("The Body Keeps the Score", "Bessel van der Kolk"),
        SeedBook("Games People Play", "Eric Berne"),
        SeedBook("The Man Who Mistook His Wife for a Hat", "Oliver Sacks"),
        SeedBook("Quiet", "Susan Cain"),
        SeedBook("Attached", "Amir Levine e Rachel Heller"),
        SeedBook("Drive", "Daniel Pink"),
        SeedBook("The Denial of Death", "Ernest Becker"),
        SeedBook("Blink", "Malcolm Gladwell"),
        SeedBook("Outliers", "Malcolm Gladwell"),
        SeedBook("Nudge", "Richard H. Thaler e Cass R. Sunstein"),
        SeedBook("The Interpretation of Dreams", "Sigmund Freud"),
        SeedBook("Civilization and Its Discontents", "Sigmund Freud"),
        SeedBook("On Becoming a Person", "Carl Rogers"),
        SeedBook("The Gift of Therapy", "Irvin D. Yalom"),
        SeedBook("Emotional Agility", "Susan David"),
        SeedBook("The Paradox of Choice", "Barry Schwartz"),
        SeedBook("Why Zebras Don't Get Ulcers", "Robert Sapolsky"),
    ),
    "filosofia": (
        SeedBook("A Republica", "Platao"),
        SeedBook("Apologia de Socrates", "Platao"),
        SeedBook("Fedon", "Platao"),
        SeedBook("Etica a Nicomaco", "Aristoteles"),
        SeedBook("Politica", "Aristoteles"),
        SeedBook("Meditacoes", "Marco Aurelio"),
        SeedBook("Manual de Epicteto", "Epicteto"),
        SeedBook("Cartas de um Estoico", "Seneca"),
        SeedBook("O Principe", "Nicolau Maquiavel"),
        SeedBook("Discursos sobre a Primeira Decada de Tito Livio", "Nicolau Maquiavel"),
        SeedBook("Leviata", "Thomas Hobbes"),
        SeedBook("Segundo Tratado sobre o Governo", "John Locke"),
        SeedBook("O Contrato Social", "Jean-Jacques Rousseau"),
        SeedBook("Discurso sobre a Origem da Desigualdade", "Jean-Jacques Rousseau"),
        SeedBook("Investigacao sobre o Entendimento Humano", "David Hume"),
        SeedBook("Fundamentacao da Metafisica dos Costumes", "Immanuel Kant"),
        SeedBook("Critica da Razao Pura", "Immanuel Kant"),
        SeedBook("O que e Esclarecimento?", "Immanuel Kant"),
        SeedBook("Utilitarismo", "John Stuart Mill"),
        SeedBook("Sobre a Liberdade", "John Stuart Mill"),
        SeedBook("Assim Falou Zaratustra", "Friedrich Nietzsche"),
        SeedBook("Alem do Bem e do Mal", "Friedrich Nietzsche"),
        SeedBook("Genealogia da Moral", "Friedrich Nietzsche"),
        SeedBook("O Mito de Sisifo", "Albert Camus"),
        SeedBook("O Homem Revoltado", "Albert Camus"),
        SeedBook("Ser e Tempo", "Martin Heidegger"),
        SeedBook("O Existencialismo e um Humanismo", "Jean-Paul Sartre"),
        SeedBook("Temor e Tremor", "Soren Kierkegaard"),
        SeedBook("Tao Te Ching", "Laozi"),
        SeedBook("Analectos", "Confucio"),
        SeedBook("A Condicao Humana", "Hannah Arendt"),
    ),
    "economia": (
        SeedBook("A Riqueza das Nacoes", "Adam Smith"),
        SeedBook("O Capital", "Karl Marx"),
        SeedBook("A Teoria Geral do Emprego, do Juro e da Moeda", "John Maynard Keynes"),
        SeedBook("Capitalismo e Liberdade", "Milton Friedman"),
        SeedBook("O Caminho da Servidao", "Friedrich Hayek"),
        SeedBook("Economia em Uma Unica Licao", "Henry Hazlitt"),
        SeedBook("Freakonomics", "Steven D. Levitt e Stephen J. Dubner"),
        SeedBook("Poor Economics", "Abhijit V. Banerjee e Esther Duflo"),
        SeedBook("Good Economics for Hard Times", "Abhijit V. Banerjee e Esther Duflo"),
        SeedBook("Why Nations Fail", "Daron Acemoglu e James A. Robinson"),
        SeedBook("Capital in the Twenty-First Century", "Thomas Piketty"),
        SeedBook("The Price of Inequality", "Joseph E. Stiglitz"),
        SeedBook("Development as Freedom", "Amartya Sen"),
        SeedBook("Misbehaving", "Richard H. Thaler"),
        SeedBook("The Ascent of Money", "Niall Ferguson"),
        SeedBook("Debt: The First 5000 Years", "David Graeber"),
        SeedBook("The Worldly Philosophers", "Robert L. Heilbroner"),
        SeedBook("Lords of Finance", "Liaquat Ahamed"),
        SeedBook("The Affluent Society", "John Kenneth Galbraith"),
        SeedBook("The Great Transformation", "Karl Polanyi"),
        SeedBook("This Time Is Different", "Carmen M. Reinhart e Kenneth S. Rogoff"),
        SeedBook("Capitalism, Socialism and Democracy", "Joseph A. Schumpeter"),
        SeedBook("Small Is Beautiful", "E. F. Schumacher"),
        SeedBook("The Undercover Economist", "Tim Harford"),
        SeedBook("The Deficit Myth", "Stephanie Kelton"),
        SeedBook("The Entrepreneurial State", "Mariana Mazzucato"),
        SeedBook("The Big Short", "Michael Lewis"),
        SeedBook("Flash Boys", "Michael Lewis"),
        SeedBook("Doughnut Economics", "Kate Raworth"),
        SeedBook("Basic Economics", "Thomas Sowell"),
    ),
    "ficcao_moderna": (
        SeedBook("1984", "George Orwell"),
        SeedBook("A Revolucao dos Bichos", "George Orwell"),
        SeedBook("Admiravel Mundo Novo", "Aldous Huxley"),
        SeedBook("Fahrenheit 451", "Ray Bradbury"),
        SeedBook("Matadouro Cinco", "Kurt Vonnegut"),
        SeedBook("Catch-22", "Joseph Heller"),
        SeedBook("O Nome da Rosa", "Umberto Eco"),
        SeedBook("A Insustentavel Leveza do Ser", "Milan Kundera"),
        SeedBook("O Mestre e Margarida", "Mikhail Bulgakov"),
        SeedBook("Doutor Jivago", "Boris Pasternak"),
        SeedBook("Cem Anos de Solidao", "Gabriel Garcia Marquez"),
        SeedBook("O Amor nos Tempos do Colera", "Gabriel Garcia Marquez"),
        SeedBook("Cronica de uma Morte Anunciada", "Gabriel Garcia Marquez"),
        SeedBook("A Casa dos Espiritos", "Isabel Allende"),
        SeedBook("A Festa do Bode", "Mario Vargas Llosa"),
        SeedBook("Pedro Paramo", "Juan Rulfo"),
        SeedBook("O Jogo da Amarelinha", "Julio Cortazar"),
        SeedBook("Ficcoes", "Jorge Luis Borges"),
        SeedBook("O Aleph", "Jorge Luis Borges"),
        SeedBook("Ensaio sobre a Cegueira", "Jose Saramago"),
        SeedBook("O Evangelho Segundo Jesus Cristo", "Jose Saramago"),
        SeedBook("Memorial do Convento", "Jose Saramago"),
        SeedBook("A Hora da Estrela", "Clarice Lispector"),
        SeedBook("A Paixao Segundo G.H.", "Clarice Lispector"),
        SeedBook("Agua Viva", "Clarice Lispector"),
        SeedBook("Grande Sertao: Veredas", "Joao Guimaraes Rosa"),
        SeedBook("Dom Casmurro", "Machado de Assis"),
        SeedBook("Memorias Postumas de Bras Cubas", "Machado de Assis"),
        SeedBook("Quincas Borba", "Machado de Assis"),
        SeedBook("Sao Bernardo", "Graciliano Ramos"),
        SeedBook("Vidas Secas", "Graciliano Ramos"),
        SeedBook("Fogo Morto", "Jose Lins do Rego"),
        SeedBook("Coisas Desmoronam", "Chinua Achebe"),
        SeedBook("Meio Sol Amarelo", "Chimamanda Ngozi Adichie"),
        SeedBook("Desgraca", "J. M. Coetzee"),
        SeedBook("Esperando os Barbaros", "J. M. Coetzee"),
        SeedBook("O Deus das Pequenas Coisas", "Arundhati Roy"),
        SeedBook("Filhos da Meia-Noite", "Salman Rushdie"),
        SeedBook("A Fine Balance", "Rohinton Mistry"),
        SeedBook("O Tigre Branco", "Aravind Adiga"),
        SeedBook("Nunca Me Deixes", "Kazuo Ishiguro"),
        SeedBook("Os Vestigios do Dia", "Kazuo Ishiguro"),
        SeedBook("Norwegian Wood", "Haruki Murakami"),
        SeedBook("Kafka a Beira-Mar", "Haruki Murakami"),
        SeedBook("Cronica do Passaro de Corda", "Haruki Murakami"),
        SeedBook("Amada", "Toni Morrison"),
        SeedBook("Cancao de Salomao", "Toni Morrison"),
        SeedBook("Homem Invisivel", "Ralph Ellison"),
        SeedBook("Native Son", "Richard Wright"),
        SeedBook("Seus Olhos Viam Deus", "Zora Neale Hurston"),
        SeedBook("O Sol e para Todos", "Harper Lee"),
        SeedBook("A Cor Purpura", "Alice Walker"),
        SeedBook("A Estrada", "Cormac McCarthy"),
        SeedBook("Meridiano de Sangue", "Cormac McCarthy"),
        SeedBook("O Cacador de Pipas", "Khaled Hosseini"),
        SeedBook("Mil Sois Splendidos", "Khaled Hosseini"),
        SeedBook("A Vida de Pi", "Yann Martel"),
        SeedBook("A Sombra do Vento", "Carlos Ruiz Zafon"),
        SeedBook("O Tunel", "Ernesto Sabato"),
        SeedBook("Temporada de Migracao para o Norte", "Tayeb Salih"),
    ),
    "geopolitica": (
        SeedBook("Diplomacy", "Henry Kissinger"),
        SeedBook("World Order", "Henry Kissinger"),
        SeedBook("On China", "Henry Kissinger"),
        SeedBook("The Tragedy of Great Power Politics", "John J. Mearsheimer"),
        SeedBook("The Revenge of Geography", "Robert D. Kaplan"),
        SeedBook("Prisoners of Geography", "Tim Marshall"),
        SeedBook("The Grand Chessboard", "Zbigniew Brzezinski"),
        SeedBook("The Clash of Civilizations and the Remaking of World Order", "Samuel P. Huntington"),
        SeedBook("The End of History and the Last Man", "Francis Fukuyama"),
        SeedBook("Destined for War", "Graham Allison"),
        SeedBook("The Rise and Fall of the Great Powers", "Paul Kennedy"),
        SeedBook("The Cold War", "Odd Arne Westad"),
        SeedBook("The Sleepwalkers", "Christopher Clark"),
        SeedBook("The Guns of August", "Barbara W. Tuchman"),
        SeedBook("The New Map", "Daniel Yergin"),
        SeedBook("The Accidental Superpower", "Peter Zeihan"),
        SeedBook("The Future Is Asian", "Parag Khanna"),
        SeedBook("Connectography", "Parag Khanna"),
        SeedBook("The Peloponnesian War", "Thucydides"),
        SeedBook("The Origins of Political Order", "Francis Fukuyama"),
        SeedBook("Political Order and Political Decay", "Francis Fukuyama"),
        SeedBook("The Power of Geography", "Tim Marshall"),
        SeedBook("The New Silk Roads", "Peter Frankopan"),
        SeedBook("The Revenge of Power", "Moises Naim"),
        SeedBook("The Road to Unfreedom", "Timothy Snyder"),
        SeedBook("Bloodlands", "Timothy Snyder"),
        SeedBook("The Strong Do What They Can and the Weak Suffer What They Must", "Yanis Varoufakis"),
        SeedBook("Sea Power", "James Stavridis"),
        SeedBook("The Return of Marco Polo's World", "Robert D. Kaplan"),
        SeedBook("The Absent Superpower", "Peter Zeihan"),
    ),
    "historia": (
        SeedBook("Sapiens", "Yuval Noah Harari"),
        SeedBook("Guns, Germs, and Steel", "Jared Diamond"),
        SeedBook("Collapse", "Jared Diamond"),
        SeedBook("The Dawn of Everything", "David Graeber e David Wengrow"),
        SeedBook("A People's History of the United States", "Howard Zinn"),
        SeedBook("The Making of the English Working Class", "E. P. Thompson"),
        SeedBook("The Age of Revolution", "Eric Hobsbawm"),
        SeedBook("The Age of Capital", "Eric Hobsbawm"),
        SeedBook("The Age of Empire", "Eric Hobsbawm"),
        SeedBook("Age of Extremes", "Eric Hobsbawm"),
        SeedBook("The Histories", "Herodotus"),
        SeedBook("SPQR", "Mary Beard"),
        SeedBook("Rubicon", "Tom Holland"),
        SeedBook("The Roman Revolution", "Ronald Syme"),
        SeedBook("The Crusades Through Arab Eyes", "Amin Maalouf"),
        SeedBook("The Black Jacobins", "C. L. R. James"),
        SeedBook("Bury My Heart at Wounded Knee", "Dee Brown"),
        SeedBook("King Leopold's Ghost", "Adam Hochschild"),
        SeedBook("The Anarchy", "William Dalrymple"),
        SeedBook("Jerusalem: The Biography", "Simon Sebag Montefiore"),
        SeedBook("India After Gandhi", "Ramachandra Guha"),
        SeedBook("The Better Angels of Our Nature", "Steven Pinker"),
        SeedBook("A Little History of the World", "E. H. Gombrich"),
        SeedBook("1491", "Charles C. Mann"),
        SeedBook("1493", "Charles C. Mann"),
        SeedBook("The Warmth of Other Suns", "Isabel Wilkerson"),
        SeedBook("Open Veins of Latin America", "Eduardo Galeano"),
        SeedBook("Postwar", "Tony Judt"),
        SeedBook("The World: A Family History", "Simon Sebag Montefiore"),
        SeedBook("Caste", "Isabel Wilkerson"),
    ),
    "ciencia": (
        SeedBook("A Origem das Especies", "Charles Darwin"),
        SeedBook("The Selfish Gene", "Richard Dawkins"),
        SeedBook("The Gene", "Siddhartha Mukherjee"),
        SeedBook("The Emperor of All Maladies", "Siddhartha Mukherjee"),
        SeedBook("Cosmos", "Carl Sagan"),
        SeedBook("The Demon-Haunted World", "Carl Sagan"),
        SeedBook("The Structure of Scientific Revolutions", "Thomas S. Kuhn"),
        SeedBook("Silent Spring", "Rachel Carson"),
        SeedBook("The Sixth Extinction", "Elizabeth Kolbert"),
        SeedBook("The Immortal Life of Henrietta Lacks", "Rebecca Skloot"),
        SeedBook("The Double Helix", "James D. Watson"),
        SeedBook("Surely You're Joking, Mr. Feynman!", "Richard P. Feynman"),
        SeedBook("What Is Life?", "Erwin Schrodinger"),
        SeedBook("Godel, Escher, Bach", "Douglas R. Hofstadter"),
        SeedBook("Thinking in Systems", "Donella H. Meadows"),
        SeedBook("The Systems View of Life", "Fritjof Capra e Pier Luigi Luisi"),
        SeedBook("How to Lie with Statistics", "Darrell Huff"),
        SeedBook("Factfulness", "Hans Rosling"),
        SeedBook("The Information", "James Gleick"),
        SeedBook("Chaos", "James Gleick"),
        SeedBook("The Black Swan", "Nassim Nicholas Taleb"),
        SeedBook("Skin in the Game", "Nassim Nicholas Taleb"),
        SeedBook("Range", "David Epstein"),
        SeedBook("Superforecasting", "Philip E. Tetlock e Dan Gardner"),
        SeedBook("A Brief History of Time", "Stephen Hawking"),
    ),
    "sociologia": (
        SeedBook("The Presentation of Self in Everyday Life", "Erving Goffman"),
        SeedBook("Bowling Alone", "Robert D. Putnam"),
        SeedBook("Amusing Ourselves to Death", "Neil Postman"),
        SeedBook("Understanding Media", "Marshall McLuhan"),
        SeedBook("The Shallows", "Nicholas Carr"),
        SeedBook("The Age of Surveillance Capitalism", "Shoshana Zuboff"),
        SeedBook("Manufacturing Consent", "Edward S. Herman e Noam Chomsky"),
        SeedBook("Orientalism", "Edward W. Said"),
        SeedBook("Discipline and Punish", "Michel Foucault"),
        SeedBook("The History of Sexuality, Volume 1", "Michel Foucault"),
        SeedBook("Distinction", "Pierre Bourdieu"),
        SeedBook("The Society of the Spectacle", "Guy Debord"),
        SeedBook("Liquid Modernity", "Zygmunt Bauman"),
        SeedBook("Pedagogy of the Oppressed", "Paulo Freire"),
        SeedBook("The Souls of Black Folk", "W. E. B. Du Bois"),
        SeedBook("The Fire Next Time", "James Baldwin"),
        SeedBook("Between the World and Me", "Ta-Nehisi Coates"),
        SeedBook("We Should All Be Feminists", "Chimamanda Ngozi Adichie"),
        SeedBook("Feminism Is for Everybody", "bell hooks"),
        SeedBook("Ain't I a Woman", "bell hooks"),
        SeedBook("The Second Sex", "Simone de Beauvoir"),
        SeedBook("The Feminine Mystique", "Betty Friedan"),
        SeedBook("Evicted", "Matthew Desmond"),
        SeedBook("No Logo", "Naomi Klein"),
        SeedBook("The Sociological Imagination", "C. Wright Mills"),
    ),
    "biografia": (
        SeedBook("Long Walk to Freedom", "Nelson Mandela"),
        SeedBook("The Diary of a Young Girl", "Anne Frank"),
        SeedBook("Educated", "Tara Westover"),
        SeedBook("The Autobiography of Malcolm X", "Malcolm X e Alex Haley"),
        SeedBook("I Know Why the Caged Bird Sings", "Maya Angelou"),
        SeedBook("Night", "Elie Wiesel"),
        SeedBook("Churchill: Walking with Destiny", "Andrew Roberts"),
        SeedBook("Steve Jobs", "Walter Isaacson"),
        SeedBook("Einstein: His Life and Universe", "Walter Isaacson"),
        SeedBook("Leonardo da Vinci", "Walter Isaacson"),
        SeedBook("Alexander Hamilton", "Ron Chernow"),
        SeedBook("Catherine the Great: Portrait of a Woman", "Robert K. Massie"),
        SeedBook("Personal History", "Katharine Graham"),
        SeedBook("Born a Crime", "Trevor Noah"),
        SeedBook("When Breath Becomes Air", "Paul Kalanithi"),
        SeedBook("Dreams from My Father", "Barack Obama"),
        SeedBook("Open", "Andre Agassi"),
        SeedBook("Shoe Dog", "Phil Knight"),
        SeedBook("The Snowball", "Alice Schroeder"),
        SeedBook("The Story of My Experiments with Truth", "Mahatma Gandhi"),
        SeedBook("My Life and Work", "Henry Ford"),
        SeedBook("Benjamin Franklin: An American Life", "Walter Isaacson"),
        SeedBook("Just as I Am", "Cicely Tyson"),
        SeedBook("Up From Slavery", "Booker T. Washington"),
    ),
}


def build_balanced_catalog() -> list[dict[str, object]]:
    queues = {key: deque(value) for key, value in SEED_BOOKS.items()}
    category_offsets = {key: 0 for key in SEED_BOOKS}
    payload: list[dict[str, object]] = []
    day = 1

    while any(queues.values()):
        for category in CATEGORY_ORDER:
            if not queues[category]:
                continue
            seed = queues[category].popleft()
            offset = category_offsets[category]
            payload.append(_build_entry(day=day, category=category, offset=offset, seed=seed))
            category_offsets[category] += 1
            day += 1

    if len(payload) != 365:
        raise ValueError(f"Catalogo balanceado precisa gerar 365 itens; gerou {len(payload)}.")
    return payload


def _build_entry(day: int, category: str, offset: int, seed: SeedBook) -> dict[str, object]:
    profile = PROFILES[category]
    theme = profile.themes[offset % len(profile.themes)]
    return {
        "day": day,
        "title": seed.title,
        "author": seed.author,
        "category": profile.label,
        "theme": theme,
        "key_ideas": [item.format(theme=theme) for item in profile.key_idea_templates],
        "practical_applications": [item.format(theme=theme) for item in profile.practical_templates],
        "reflection_question": profile.reflection_template.format(theme=theme),
        "optional_quote": None,
    }
